// ::: Code Generated by Copilot [4C91AA14-83C8-4B0A-A8BE-3E5D790D3956]. This comment will be removed automatically after the file is saved :::
const fs = require('fs');
const path = require('path');
const { app, safeStorage } = require('electron');

const SECRET_KEYS = ['apiToken', 'refreshToken'];

const DEFAULTS = {
  baseUrl: 'https://ops.evconnect.com',
  // ::: Code Generated by Copilot [2eab5736-0cc0-4212-9f55-78f119f84682]. This comment will be removed automatically after the file is saved :::
  ntfyTopic: 'ev-crossman',
  locationsPath: '/mobile/rest/v6/users/current/locations',
  authPath: '/mobile/rest/v6/auth',
  networkId: 'ev-connect',
  appVersion: '6.1.4',
  pollingMinutes: 15,
  playSound: true,
  startAtLogin: false,
  email: '',
  apiToken: '',
  refreshToken: '',
};

let cache = null;

function filePath() {
  return path.join(app.getPath('userData'), 'settings.json');
}

function encrypt(value) {
  if (!value) return '';
  if (!safeStorage.isEncryptionAvailable()) return `plain:${value}`;
  return `enc:${safeStorage.encryptString(value).toString('base64')}`;
}

function decrypt(value) {
  if (!value) return '';
  if (value.startsWith('plain:')) return value.slice(6);
  if (!value.startsWith('enc:')) return value;
  try {
    return safeStorage.decryptString(Buffer.from(value.slice(4), 'base64'));
  } catch {
    return '';
  }
}

function load() {
  if (cache) return cache;
  let stored = {};
  try {
    stored = JSON.parse(fs.readFileSync(filePath(), 'utf8'));
  } catch {
    stored = {};
  }
  // ::: Code Generated by Copilot [4C91AA14-83C8-4B0A-A8BE-3E5D790D3956]. This comment will be removed automatically after the file is saved :::
  if (Object.hasOwn(stored, 'password')) {
    delete stored.password;
    fs.writeFileSync(filePath(), JSON.stringify(stored, null, 2), { mode: 0o600 });
  }
  cache = { ...DEFAULTS, ...stored };
  for (const key of SECRET_KEYS) cache[key] = decrypt(cache[key]);
  if (![0, 5, 15, 30].includes(cache.pollingMinutes)) cache.pollingMinutes = 15;
  return cache;
}

function save(patch) {
  const next = { ...load(), ...patch };
  if (![0, 5, 15, 30].includes(next.pollingMinutes)) next.pollingMinutes = 15;
  cache = next;

  const onDisk = { ...next };
  for (const key of SECRET_KEYS) onDisk[key] = encrypt(next[key]);
  fs.mkdirSync(path.dirname(filePath()), { recursive: true });
  fs.writeFileSync(filePath(), JSON.stringify(onDisk, null, 2), { mode: 0o600 });
  return cache;
}

module.exports = { load, save, DEFAULTS };
